### PR TITLE
"larexamples

### PR DESCRIPTION
**Pull request by lgarren**

### CODE REVIEW

**Comment by lgarren** [comment]
code-checks

On 11/21/19 12:35 PM, Fermilab build bot account wrote:

A new Pull Request was created by @lgarren<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lgarren&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=jgWTBgY-XkUJ_pZDzVCQLTnskYDKwtQRNJNaRXM3TMM&s=kQBrSd5UUq4CtFpoOJwz8_xE6MUXLnMunBxPbcXT4IU&e=> (Lynn Garren) for develop.

It involves the following packages:

larexamples

@tomjunk<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tomjunk&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=jgWTBgY-XkUJ_pZDzVCQLTnskYDKwtQRNJNaRXM3TMM&s=igWNAcu9e9jafhxOcMnrJiILbdJLDymoAySO6Riky4E&e=>, @knoepfel<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_knoepfel&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=jgWTBgY-XkUJ_pZDzVCQLTnskYDKwtQRNJNaRXM3TMM&s=fy2MHqc3e1ExzLSyxEHNqU8v-qNP-0KE8fNnQcQsaWw&e=>, @lgarren<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lgarren&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=jgWTBgY-XkUJ_pZDzVCQLTnskYDKwtQRNJNaRXM3TMM&s=kQBrSd5UUq4CtFpoOJwz8_xE6MUXLnMunBxPbcXT4IU&e=>, @gartung<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_gartung&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=jgWTBgY-XkUJ_pZDzVCQLTnskYDKwtQRNJNaRXM3TMM&s=rM5lWhsfCiUVmkpmt3Bz-10CEtsGIR6rFLw0VD1aHH8&e=>, @FNALbuild<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_FNALbuild&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=jgWTBgY-XkUJ_pZDzVCQLTnskYDKwtQRNJNaRXM3TMM&s=NRatmYa5VrRHVPXC_QuQidCmsNItJ2Z1FZpof7VVbpw&e=>, @dladams<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dladams&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=jgWTBgY-XkUJ_pZDzVCQLTnskYDKwtQRNJNaRXM3TMM&s=--qJY638fQoBveeSKVvUG9qTIwrcSsaZ8Ym7YMcw5F4&e=>, @erica-snider<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_erica-2Dsnider&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=jgWTBgY-XkUJ_pZDzVCQLTnskYDKwtQRNJNaRXM3TMM&s=XgchwXSZT_K8tUPeO-RPpRhG4sYOMyZNCnlf_WSSQtc&e=>, @yangtj207<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_yangtj207&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=jgWTBgY-XkUJ_pZDzVCQLTnskYDKwtQRNJNaRXM3TMM&s=sYcYSRljAe1hdAFADRzFQ_i-hKIX4vCpH--bzmRf1nM&e=>, @SFBayLaser<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_SFBayLaser&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=jgWTBgY-XkUJ_pZDzVCQLTnskYDKwtQRNJNaRXM3TMM&s=FKosZ0SaiYQektVGKaYzbw_0Cdi0jaEtzuoF9J4dNxA&e=>, @chalt007<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_chalt007&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=jgWTBgY-XkUJ_pZDzVCQLTnskYDKwtQRNJNaRXM3TMM&s=Jir5edUNxvIECDzDu8nqLq9m9-2vkR46muQfqj4LfeI&e=>, @vitodb<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_vitodb&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=jgWTBgY-XkUJ_pZDzVCQLTnskYDKwtQRNJNaRXM3TMM&s=rTUjgM0Lf6dQkDai4rxFHydRktsyYUjLQr4U-Fee8_w&e=>, @chissg<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_chissg&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=jgWTBgY-XkUJ_pZDzVCQLTnskYDKwtQRNJNaRXM3TMM&s=_KawXoSUBXwqdgXGHMrwpQ2hBFnllTXNyWlA91-FLp0&e=>, @hgreenlee<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_hgreenlee&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=jgWTBgY-XkUJ_pZDzVCQLTnskYDKwtQRNJNaRXM3TMM&s=EuhItwdYDSr7Q-lIV-4Ftv2TvOdb2I5jk9ET2bFL5Jc&e=> can you please review it and eventually sign? Thanks.
@gartung<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_gartung&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=jgWTBgY-XkUJ_pZDzVCQLTnskYDKwtQRNJNaRXM3TMM&s=rM5lWhsfCiUVmkpmt3Bz-10CEtsGIR6rFLw0VD1aHH8&e=> this is something you requested to watch as well.

cms-bot commands are listed here<https://urldefense.proofpoint.com/v2/url?u=http-3A__cms-2Dsw.github.io_cms-2Dbot-2Dcmssw-2Dcmds.html&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=jgWTBgY-XkUJ_pZDzVCQLTnskYDKwtQRNJNaRXM3TMM&s=oeo3AScEU0bQm1NTaHfiv82NPahXqb-Q2l8VM4xynd8&e=>

**Comment by lgarren** [comment]
code-checks

**Comment by gartung** [comment]
+1

**Comment by gartung** [comment]
abort

**Comment by gartung** [comment]
merge

**Pull request merged**
